allowBuilds:
  esbuild: true
  opencode-ai: true
minimumReleaseAgeExclude:
  - "@opencode-ai/sdk@1.18.1"
  - opencode-ai@1.18.1
  - opencode-darwin-arm64@1.18.1
  - opencode-darwin-x64-baseline@1.18.1
  - opencode-darwin-x64@1.18.1
  - opencode-linux-arm64-musl@1.18.1
  - opencode-linux-arm64@1.18.1
  - opencode-linux-x64-baseline-musl@1.18.1
  - opencode-linux-x64-baseline@1.18.1
  - opencode-linux-x64-musl@1.18.1
  - opencode-linux-x64@1.18.1
  - opencode-windows-arm64@1.18.1
  - opencode-windows-x64-baseline@1.18.1
  - opencode-windows-x64@1.18.1
